name: awiesm_docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter-book
  - matplotlib
  - pip:
    - sphinxcontrib-youtube
prefix: /Users/pgierz/opt/miniconda3/envs/awiesm_docs
